"""add answers table

Revision ID: 0a7538c2b6fb
Revises: 
Create Date: 2023-03-24 00:48:12.981297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7538c2b6fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_gpt_answers',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('input', sa.String(length=120), nullable=True),
                    sa.Column('answer', sa.String(length=120), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    # sa.UniqueConstraint('input')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_gpt_answers')
    # ### end Alembic commands ###
