"""description_of_migration

Revision ID: bb37fd159b1c
Revises: 0a7538c2b6fb
Create Date: 2023-04-02 18:15:03.292564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb37fd159b1c'
down_revision = '0a7538c2b6fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
